import React, { useEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import FileUpload, { FileUploadHandle } from '../../components/FileUpload';
import type { ApplicationDocument, UploadedFile } from '../../types/fileUpload';
import { firUploadEndpoints, getFurtherInformationRequest, getFurtherInformationRequests, submitFurtherInformationResponse } from './fir.service';
import type { FurtherInformationRequest } from './fir.types';

const LABELS: Record<string, string> = {
  FIR_PLAN_INFORMATION: 'Plan information', FIR_ENVIRONMENTAL_AND_ARCHAEOLOGICAL: 'Environmental and archaeological', FIR_SUPPORTING_DOCUMENTS: 'Supporting documents',
  FIR_NWL_NOTICE_TO_REMOVE: 'Notice to Remove', FIR_NWL_EXPIRED_WAYLEAVE: 'Expired wayleave', FIR_NWL_TERMINATED_WAYLEAVE: 'Terminated wayleave', FIR_NWL_NOTICE_TO_TERMINATE: 'Notice to Terminate', FIR_NWL_WAYLEAVE_NOTICE: 'Wayleave notice', FIR_NWL_LAND_REGISTRY: 'Land registry', FIR_NWL_SITE_INFORMATION: 'Site information', FIR_NWL_UNREGISTERED_LAND: 'Unregistered land details', FIR_NWL_APPLICATION_PLAN: 'Application plan', FIR_NWL_EVIDENCE_OF_NEGOTIATIONS: 'Evidence of negotiations', FIR_NWL_ADDITIONAL_DOCUMENTS: 'Additional documents',
};

const displayDate = (date: string) => new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`));
const status = (value: string) => value === 'RESPONDED' ? 'Completed' : value === 'OPEN' ? 'Not completed' : value.replaceAll('_', ' ');
const basePath = (pathname: string, applicationId: string) => `${pathname.startsWith('/nwl/') ? '/nwl' : '/s-37'}/${applicationId}`;

const RequestCard = ({ request, action }: { request: FurtherInformationRequest; action?: React.ReactNode }) => <section className="govuk-summary-card"><div className="govuk-summary-card__title-wrapper"><h2 className="govuk-summary-card__title">Further information request</h2></div><dl className="govuk-summary-list"><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Date requested</dt><dd className="govuk-summary-list__value">{displayDate(request.createdAt)}</dd></div><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Request from case officer</dt><dd className="govuk-summary-list__value">{request.requestText}</dd></div><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Deadline to respond</dt><dd className="govuk-summary-list__value">{displayDate(request.deadlineAt)}</dd></div><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Status</dt><dd className="govuk-summary-list__value"><strong className="govuk-tag govuk-tag--blue">{status(request.status)}</strong></dd></div>{request.response && <><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Submitted</dt><dd className="govuk-summary-list__value">{new Intl.DateTimeFormat('en-GB', { dateStyle: 'long' }).format(new Date(request.response.submittedAt))}</dd></div><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Document types selected</dt><dd className="govuk-summary-list__value">{request.response.documentCategories.map((category) => <div key={category}>{LABELS[category] || category}</div>)}</dd></div>{request.response.documents.map((document) => <div className="govuk-summary-list__row" key={document.documentId}><dt className="govuk-summary-list__key">{LABELS[document.documentCategory] || document.documentCategory}</dt><dd className="govuk-summary-list__value">{document.filename}</dd></div>)}{request.response.responseText && <div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Additional comments</dt><dd className="govuk-summary-list__value">{request.response.responseText}</dd></div>}</>}</dl>{action}</section>;

export const FurtherInformationRequestsPage: React.FC = () => {
  const { applicationId } = useParams<{ applicationId: string }>(); const location = useLocation(); const [requests, setRequests] = useState<FurtherInformationRequest[]>([]); const [error, setError] = useState('');
  useEffect(() => { if (applicationId) void getFurtherInformationRequests(applicationId).then(setRequests).catch((reason: Error) => setError(reason.message)); }, [applicationId]);
  const base = basePath(location.pathname, applicationId || ''); const open = requests.filter((request) => request.status === 'OPEN'); const complete = requests.filter((request) => request.status !== 'OPEN');
  return <div className="govuk-width-container"><Link className="govuk-back-link" to={`${base}/application-summary`}>Back</Link><h1 className="govuk-heading-l">Further information requests</h1>{error && <div className="govuk-error-summary" role="alert"><h2 className="govuk-error-summary__title">There is a problem</h2><p>{error}</p></div>}{open.map((request) => <RequestCard key={request.furtherInformationRequestId} request={request} action={<Link className="govuk-button" to={`${base}/further-information-requests/${request.furtherInformationRequestId}/respond`}>Provide information</Link>} />)}{complete.length > 0 && <><h2 className="govuk-heading-m">Completed requests</h2>{complete.map((request) => <RequestCard key={request.furtherInformationRequestId} request={request} />)}</>}</div>;
};

export const FurtherInformationResponsePage: React.FC = () => {
  const { applicationId, requestId } = useParams<{ applicationId: string; requestId: string }>(); const location = useLocation(); const navigate = useNavigate(); const uploadRefs = useRef<Record<string, FileUploadHandle | null>>({}); const [request, setRequest] = useState<FurtherInformationRequest | null>(null); const [selected, setSelected] = useState<string[]>([]); const [documents, setDocuments] = useState<ApplicationDocument[]>([]); const [comments, setComments] = useState(''); const [uploading, setUploading] = useState<'yes' | 'no'>('no'); const [error, setError] = useState('');
  useEffect(() => { if (applicationId && requestId) void getFurtherInformationRequest(applicationId, requestId).then(setRequest).catch((reason: Error) => setError(reason.message)); }, [applicationId, requestId]);
  if (!applicationId || !requestId) return null; const base = basePath(location.pathname, applicationId);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); const uploadResults = uploading === 'yes' ? await Promise.all(selected.map((category) => uploadRefs.current[category]?.triggerUpload())) : []; const scanError = uploadResults.flatMap((result) => result?.scanErrors || [])[0]; if (scanError) { setError(scanError); return; } const allDocuments = [...documents, ...uploadResults.flatMap((result) => result?.applicationDocuments || [])]; if (!comments.trim() && allDocuments.length === 0) { setError('Provide information or upload a document'); return; } try { await submitFurtherInformationResponse(applicationId, requestId, { responseText: comments, documentCategories: selected, documentLinks: allDocuments.map((document) => ({ documentId: document.documentId, documentCategory: document.category })) }); navigate(`${base}/further-information-requests/${requestId}/submitted`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The information could not be submitted'); } };
  return <div className="govuk-width-container"><Link className="govuk-back-link" to={`${base}/further-information-requests`}>Back</Link><h1 className="govuk-heading-l">Provide the information requested</h1>{error && <div className="govuk-error-summary" role="alert"><h2 className="govuk-error-summary__title">There is a problem</h2><p>{error}</p></div>}{request && <form onSubmit={submit} noValidate><div className="govuk-form-group"><fieldset className="govuk-fieldset"><legend className="govuk-fieldset__legend govuk-fieldset__legend--s">Are you uploading documents as part of this request?</legend><div className="govuk-radios"><div className="govuk-radios__item"><input className="govuk-radios__input" id="fir-documents-yes" type="radio" checked={uploading === 'yes'} onChange={() => setUploading('yes')} /><label className="govuk-label govuk-radios__label" htmlFor="fir-documents-yes">Yes</label></div><div className="govuk-radios__item"><input className="govuk-radios__input" id="fir-documents-no" type="radio" checked={uploading === 'no'} onChange={() => setUploading('no')} /><label className="govuk-label govuk-radios__label" htmlFor="fir-documents-no">No</label></div></div></fieldset></div>{uploading === 'yes' && <fieldset className="govuk-fieldset"><legend className="govuk-fieldset__legend govuk-fieldset__legend--m">Select the type of documents you will provide</legend><div className="govuk-checkboxes">{request.requestedDocumentCategories.map((category) => <div className="govuk-checkboxes__item" key={category}><input className="govuk-checkboxes__input" id={category} type="checkbox" checked={selected.includes(category)} onChange={() => setSelected((current) => current.includes(category) ? current.filter((item) => item !== category) : [...current, category])} /><label className="govuk-label govuk-checkboxes__label" htmlFor={category}>{LABELS[category] || category}</label></div>)}</div>{selected.map((category) => <FileUpload key={category} ref={(instance) => { uploadRefs.current[category] = instance; }} title={`Upload ${LABELS[category] || category}`} applicationId={applicationId} category={category} prefix={`${applicationId}/fir/${requestId}/${category}`} uploadEndpoints={firUploadEndpoints(applicationId, requestId)} onUploaded={(_files: UploadedFile[], newDocuments) => setDocuments((current) => [...current, ...newDocuments])} />)}</fieldset>}<div className="govuk-form-group"><label className="govuk-label govuk-label--s" htmlFor="fir-comments">Additional information (optional)</label><textarea className="govuk-textarea" id="fir-comments" rows={5} maxLength={4000} value={comments} onChange={(event) => setComments(event.target.value)} /></div><button className="govuk-button" type="submit">Submit</button></form>}<details className="govuk-details"><summary className="govuk-details__summary"><span className="govuk-details__summary-text">See the information request</span></summary>{request && <RequestCard request={request} />}</details></div>;
};

export const FurtherInformationSubmittedPage: React.FC = () => { const { applicationId } = useParams<{ applicationId: string }>(); const location = useLocation(); const base = basePath(location.pathname, applicationId || ''); return <div className="govuk-width-container"><div className="govuk-panel govuk-panel--confirmation"><h1 className="govuk-panel__title">Information submitted</h1></div><p className="govuk-body">This further information request is now complete and cannot be reopened.</p><h2 className="govuk-heading-m">What happens next</h2><p className="govuk-body">A case officer will review the information you have provided.</p><p className="govuk-body">Your application status will be updated when the review is complete.</p><Link className="govuk-button" to="/application-dashboard">See your applications</Link><p><Link to={`${base}/application-summary`}>View application summary</Link></p></div>; };