#!/bin/sh
# Inject runtime configuration inline into index.html
# This script is executed at container startup to inject runtime configuration

set -e

INDEX_FILE="/app/dist-serve/index.html"

# Function to escape special characters for JSON string values
escape_json() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\n/\\n/g; s/\r/\\r/g; s/\t/\\t/g'
}

# Read and escape environment variables
VITE_API_URL_ESCAPED=$(escape_json "${VITE_API_URL:-}")
VITE_API_BASE_URL_ESCAPED=$(escape_json "${VITE_API_BASE_URL:-}")
VITE_ENABLE_GA4_ESCAPED=$(escape_json "${VITE_ENABLE_GA4:-false}")
VITE_GA4_MEASUREMENT_ID_ESCAPED=$(escape_json "${VITE_GA4_MEASUREMENT_ID:-}")
VITE_GTM_ID_ESCAPED=$(escape_json "${VITE_GTM_ID:-}")
VITE_ENABLE_GTM_ESCAPED=$(escape_json "${VITE_ENABLE_GTM:-false}")
VITE_DISABLE_TELEMETRY_ESCAPED=$(escape_json "${VITE_DISABLE_TELEMETRY:-false}")
VITE_SESSION_TIMEOUT_SECONDS_ESCAPED=$(escape_json "${VITE_SESSION_TIMEOUT_SECONDS:-1800}")
VITE_SESSION_WARNING_SECONDS_ESCAPED=$(escape_json "${VITE_SESSION_WARNING_SECONDS:-120}")
VITE_LOGIN_DISABLED_ESCAPED=$(escape_json "${VITE_LOGIN_DISABLED:-false}")
VITE_DUMMY_USER_TYPE_ESCAPED=$(escape_json "${VITE_DUMMY_USER_TYPE:-developer}")
VITE_DISABLED_FORM_TYPES_ESCAPED=$(escape_json "${VITE_DISABLED_FORM_TYPES:-}")
VITE_SERVICE_NAME_ESCAPED=$(escape_json "${VITE_SERVICE_NAME:-SYEIA}")
VITE_DETAILED_FEEDBACK_SURVEY_URL_ESCAPED=$(escape_json "${VITE_DETAILED_FEEDBACK_SURVEY_URL:-#}")
VITE_ROUTER_BASENAME_ESCAPED=$(escape_json "${VITE_ROUTER_BASENAME:-/}")
VITE_RUM_APP_MONITOR_ID_ESCAPED=$(escape_json "${VITE_RUM_APP_MONITOR_ID:-}")
VITE_RUM_IDENTITY_POOL_ID_ESCAPED=$(escape_json "${VITE_RUM_IDENTITY_POOL_ID:-}")
VITE_RUM_REGION_ESCAPED=$(escape_json "${VITE_RUM_REGION:-eu-west-2}")
VITE_AWS_REGION_ESCAPED=$(escape_json "${VITE_AWS_REGION:-eu-west-2}")
VITE_SRI_MODE_ESCAPED=$(escape_json "${VITE_SRI_MODE:-report}")
VITE_TRUSTED_ORIGIN_ESCAPED=$(escape_json "${VITE_TRUSTED_ORIGIN:-}")
MODE_ESCAPED=$(escape_json "${MODE:-production}")

# Generate the inline script content
INLINE_SCRIPT="<script>window._env_={\"VITE_API_URL\":\"${VITE_API_URL_ESCAPED}\",\"VITE_API_BASE_URL\":\"${VITE_API_BASE_URL_ESCAPED}\",\"VITE_ENABLE_GA4\":\"${VITE_ENABLE_GA4_ESCAPED}\",\"VITE_GA4_MEASUREMENT_ID\":\"${VITE_GA4_MEASUREMENT_ID_ESCAPED}\",\"VITE_GTM_ID\":\"${VITE_GTM_ID_ESCAPED}\",\"VITE_ENABLE_GTM\":\"${VITE_ENABLE_GTM_ESCAPED}\",\"VITE_DISABLE_TELEMETRY\":\"${VITE_DISABLE_TELEMETRY_ESCAPED}\",\"VITE_SESSION_TIMEOUT_SECONDS\":\"${VITE_SESSION_TIMEOUT_SECONDS_ESCAPED}\",\"VITE_SESSION_WARNING_SECONDS\":\"${VITE_SESSION_WARNING_SECONDS_ESCAPED}\",\"VITE_LOGIN_DISABLED\":\"${VITE_LOGIN_DISABLED_ESCAPED}\",\"VITE_DUMMY_USER_TYPE\":\"${VITE_DUMMY_USER_TYPE_ESCAPED}\",\"VITE_DISABLED_FORM_TYPES\":\"${VITE_DISABLED_FORM_TYPES_ESCAPED}\",\"VITE_SERVICE_NAME\":\"${VITE_SERVICE_NAME_ESCAPED}\",\"VITE_DETAILED_FEEDBACK_SURVEY_URL\":\"${VITE_DETAILED_FEEDBACK_SURVEY_URL_ESCAPED}\",\"VITE_ROUTER_BASENAME\":\"${VITE_ROUTER_BASENAME_ESCAPED}\",\"VITE_RUM_APP_MONITOR_ID\":\"${VITE_RUM_APP_MONITOR_ID_ESCAPED}\",\"VITE_RUM_IDENTITY_POOL_ID\":\"${VITE_RUM_IDENTITY_POOL_ID_ESCAPED}\",\"VITE_RUM_REGION\":\"${VITE_RUM_REGION_ESCAPED}\",\"VITE_AWS_REGION\":\"${VITE_AWS_REGION_ESCAPED}\",\"VITE_SRI_MODE\":\"${VITE_SRI_MODE_ESCAPED}\",\"VITE_TRUSTED_ORIGIN\":\"${VITE_TRUSTED_ORIGIN_ESCAPED}\",\"MODE\":\"${MODE_ESCAPED}\"};</script>"

# Replace placeholder in index.html with inline script
if [ -f "$INDEX_FILE" ]; then
  sed -i "s|<!-- RUNTIME_CONFIG_PLACEHOLDER -->|$INLINE_SCRIPT|g" "$INDEX_FILE"
  echo "Runtime configuration injected inline into $INDEX_FILE"
else
  echo "ERROR: $INDEX_FILE not found!"
  exit 1
fi
