import React, { useEffect, useState } from "react";
import { S37_BASE_URL } from "../../../constants/s37";
import { Link } from "react-router-dom";
import { useGetApplicationId } from "../../../hooks/useGetApplicationId";
import ConsultationSummaryCard from "../components/SummaryCard";
import { useConsultationDetails } from "../../../hooks/useConsultationDetails";
import { useAuthUser } from "../../../hooks/useAuthUser";
import { generateLpaConsultationForm, getDocumentDownloadUrl } from "../../../services/documentService";

const ConsultationDetailsPage: React.FC = () => {
  const applicationId = useGetApplicationId();
  const { user } = useAuthUser();
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Scroll to top on mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

    const { consultations } = useConsultationDetails(
      applicationId,
      user?.user_id
    );

  const handleDownloadLpaForm = async () => {
    if (!applicationId) return;

    setIsGenerating(true);
    setError(null);

    try {
      const result = await generateLpaConsultationForm(applicationId);

      if ('status' in result && result.status === 'GENERATING') {
        // Document is still being generated by a concurrent request
        setError('The document is still being generated. Please try again in a few seconds.');
        setIsGenerating(false);
        return;
      }

      // Document is ready - trigger download
      const downloadUrl = getDocumentDownloadUrl(result.documentId);
      const link = document.createElement('a');
      link.href = downloadUrl;
      link.download = result.filename;
      link.click();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate document');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="govuk-width-container">
      <nav className="govuk-breadcrumbs" aria-label="Breadcrumb">
        <ol className="govuk-breadcrumbs__list">
          <li className="govuk-breadcrumbs__list-item">
            <Link
              to={`${S37_BASE_URL}/${applicationId}/task-list`}
              className="govuk-breadcrumbs__link"
            >
              Task list
            </Link>
          </li>
          <li className="govuk-breadcrumbs__list-item" aria-current="page">
            Consultation details
          </li>
        </ol>
      </nav>
      <div className="govuk-grid-row">
        <div className="govuk-grid-column-two-thirds">
          <h1 className="govuk-heading-xl">Manage consultations</h1>
          <p className="govuk-body">
            You must send a consultation request to every organisation shown on this page.
          </p>
          <div className="govuk-body">
            <p>For each organisation you must:</p>
            <ul className="govuk-list govuk-list--bullet">
              <li>send a request (or show that you have sent a request)</li>
              <li>
                upload any response received
              </li>
            </ul>
            <p>For Natural England, you can mark the consultation as 'Not required' and you will be asked to explain why it is not required.</p>
          </div>
          
 
          {consultations.map((consultation) => (
            <ConsultationSummaryCard
              key={consultation.id}
              orgName={consultation.consulteeOrganisationName}
              consultationName={
                consultation.otherConsultee ||
                consultation.consulteeOrganisationName ||
                consultation.consultationType
              }
              status={consultation.status}
              consultationId={consultation.id}
              applicationId={applicationId}
              dateRequestCreated={consultation.dateRequestCreated ?? undefined}
              dateClosed={consultation.dateClosed ?? undefined}
              objectionRaised={consultation.objectionRaised}
              closeComments={consultation.closeComments}
              responseDocuments={consultation.responseDocuments}
              respondingConsulteeName={consultation.respondingConsulteeName}
              respondingConsulteeEmail={consultation.respondingConsulteeEmail}
              notRequiredMessage={consultation.notRequiredReason}
              notRequiredDocs={consultation.notRequiredDocs}
              consultationRequestDocs={consultation.consultationRequestDocs}
              evidenceResponseNotReceivedDocs={consultation.evidenceResponseNotReceivedDocs}
            />
          ))}

          {error && (
            <div className="govuk-error-summary" data-module="govuk-error-summary" aria-labelledby="error-summary-title" role="alert">
              <h2 className="govuk-error-summary__title" id="error-summary-title">
                There is a problem
              </h2>
              <div className="govuk-error-summary__body">
                <ul className="govuk-list govuk-error-summary__list">
                  <li>{error}</li>
                </ul>
              </div>
            </div>
          )}

          <div className="govuk-button-group" style={{ marginTop: '2rem' }}>
            <button
              type="button"
              className="govuk-button"
              onClick={handleDownloadLpaForm}
              disabled={isGenerating}
            >
              {isGenerating ? 'Generating document...' : 'Download LPA Consultation Form'}
            </button>
            
            <Link
              to={`${S37_BASE_URL}/${applicationId}/task-list`}
              className="govuk-button govuk-button--secondary"
            >
              Go back to task list
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ConsultationDetailsPage;
