import React from "react";
import { APPLICATION_STATUS_ROWS } from "../constants";
import { formatCurrency, formatNumber, metricTotal, metricValue } from "../reportingUtils";
import type { MetricValues, OrganisationReportRow, StatusColour } from "../types";
import { TableRegion } from "./ReportingControls";

const StatusTag = ({ name, colour }: { name: string; colour: StatusColour }) => <strong className={`govuk-tag govuk-tag--${colour} reporting-status-tag`}>{name}</strong>;

const formatGeneratedAt = (value: string) =>
  new Date(value).toLocaleString("en-GB", { timeZone: "Europe/London", dateStyle: "medium", timeStyle: "short" });

export const ReportingSummary = ({ metrics, startDate, endDate, generatedAt, live }: { metrics: MetricValues; startDate: string; endDate: string; generatedAt?: string; live?: boolean }) => (
  <section id="summary" aria-labelledby="summary-heading">
    <h2 className="govuk-heading-l" id="summary-heading">Summary</h2>
    {live && generatedAt && <p className="govuk-hint" id="summary-live-hint">Live figures from the application database, as at {formatGeneratedAt(generatedAt)}.</p>}
    <p className="govuk-body reporting-period">{startDate} to {endDate}</p>
    <dl className="reporting-summary-grid">
      <div><dt>Applications in draft</dt><dd>{formatNumber.format(metricTotal(metrics, "s37_created", "nwl_created"))}</dd></div>
      <div><dt>Applications submitted</dt><dd>{formatNumber.format(metricTotal(metrics, "s37_submitted", "nwl_submitted"))}</dd></div>
      <div><dt>Payments made</dt><dd>{formatNumber.format(metricTotal(metrics, "s37_govpay_count", "s37_bacs_count", "nwl_govpay_count", "nwl_bacs_count"))}</dd></div>
      <div><dt>Feedback received</dt><dd>{formatNumber.format(metricValue(metrics, "feedback_received"))}</dd></div>
      <div><dt>Access requests raised</dt><dd>{formatNumber.format(metricValue(metrics, "access_requests"))}</dd></div>
      <div><dt>Pending requests</dt><dd>{formatNumber.format(metricValue(metrics, "pending_requests"))}</dd></div>
    </dl>
  </section>
);

export const ApplicationsReport = ({ metrics }: { metrics: MetricValues }) => {
  const categoryMaximum = Math.max(1, ...APPLICATION_STATUS_ROWS.map(([, , s37Key, nwlKey]) => metricTotal(metrics, s37Key, nwlKey)));
  return <section className="reporting-section" id="applications" aria-labelledby="applications-heading">
    <h2 className="govuk-heading-l" id="applications-heading">Applications</h2>
    <dl className="govuk-summary-list">
      <div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Total applications</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, "total_applications"))}</dd></div>
      <div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Total submitted</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, "total_submitted"))}</dd></div>
    </dl>
    <p className="govuk-hint">All time, as at the end of the selected period.</p>
    <h3 className="govuk-heading-s">Activity in period</h3>
    <p className="govuk-hint">In draft: created in this period and still in draft today. Submitted: submitted in this period. Total: the two added together.</p>
    <TableRegion label="Application activity table"><table className="govuk-table"><caption className="govuk-visually-hidden">Application activity by form</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Form</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">In draft</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Submitted</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Total</th></tr></thead><tbody className="govuk-table__body">{["s37", "nwl"].map((form) => <tr className="govuk-table__row" key={form}><th className="govuk-table__header" scope="row">{form.toUpperCase()}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_created`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_submitted`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, `${form}_created`, `${form}_submitted`))}</td></tr>)}<tr className="govuk-table__row"><th className="govuk-table__header" scope="row">Total</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_created", "nwl_created"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_submitted", "nwl_submitted"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_created", "nwl_created", "s37_submitted", "nwl_submitted"))}</td></tr></tbody></table></TableRegion>
    <figure className="reporting-category-chart" aria-labelledby="category-chart-heading"><figcaption className="govuk-heading-s" id="category-chart-heading">Applications by category</figcaption>{APPLICATION_STATUS_ROWS.map(([name, , s37Key, nwlKey]) => { const value = metricTotal(metrics, s37Key, nwlKey); return <div className="reporting-category-row" key={name}><span>{name}</span><div className="reporting-category-track" aria-hidden="true"><div className="reporting-category-bar" style={{ width: `${(value / categoryMaximum) * 100}%` }} /></div><strong>{formatNumber.format(value)}</strong></div>; })}</figure>
    <TableRegion label="Application status table"><table className="govuk-table"><caption className="govuk-visually-hidden">Applications by status and form</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Status</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">S37</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">NWL</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Total</th></tr></thead><tbody className="govuk-table__body">{APPLICATION_STATUS_ROWS.map(([name, colour, s37Key, nwlKey]) => <tr className="govuk-table__row" key={name}><th className="govuk-table__header" scope="row"><StatusTag name={name} colour={colour} /></th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, s37Key))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, nwlKey))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, s37Key, nwlKey))}</td></tr>)}</tbody></table></TableRegion>
  </section>;
};

export const AccessRequestsReport = ({ metrics, organisations }: { metrics: MetricValues; organisations: OrganisationReportRow[] }) => {
  // Older/snapshot report payloads may not carry these role-split fields - default to 0
  // before filtering/rendering so a missing field can't produce "undefined"/NaN in the table.
  const byRoleOrgs = organisations
    .map((row) => ({
      ...row,
      applicantRequests: row.applicantRequests ?? 0,
      agentRequests: row.agentRequests ?? 0,
      applicantPendingRequests: row.applicantPendingRequests ?? 0,
      agentPendingRequests: row.agentPendingRequests ?? 0,
    }))
    .filter((row) => row.applicantRequests > 0 || row.agentRequests > 0 || row.applicantPendingRequests > 0 || row.agentPendingRequests > 0);
  return <section className="reporting-section" id="access-requests" aria-labelledby="access-heading">
    <h2 className="govuk-heading-l" id="access-heading">Access requests</h2>
    <dl className="govuk-summary-list">{[["Received", "access_requests"], ["Accepted", "accepted_requests"], ["Rejected", "rejected_requests"], ["Pending", "pending_requests"], ["Logged-in users", "logged_in_users"]].map(([label, key]) => <div className="govuk-summary-list__row" key={key}><dt className="govuk-summary-list__key">{label}</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, key))}</dd></div>)}</dl>
    <h3 className="govuk-heading-s">By role</h3>
    <TableRegion label="Access requests by role table"><table className="govuk-table"><caption className="govuk-visually-hidden">Access requests and pending requests by applicant or agent role</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Role</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Received</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Pending</th></tr></thead><tbody className="govuk-table__body">
      <tr className="govuk-table__row"><th className="govuk-table__header" scope="row">Applicant</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, "applicant_requests"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, "applicant_pending_requests"))}</td></tr>
      <tr className="govuk-table__row"><th className="govuk-table__header" scope="row">Agent</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, "agent_requests"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, "agent_pending_requests"))}</td></tr>
    </tbody></table></TableRegion>
    <h3 className="govuk-heading-s">By role and organisation</h3>
    <TableRegion label="Access requests by role and organisation table"><table className="govuk-table"><caption className="govuk-visually-hidden">Access requests and pending requests by organisation, split by applicant or agent role</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Organisation</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Applicant received</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Applicant pending</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Agent received</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Agent pending</th></tr></thead><tbody className="govuk-table__body">{byRoleOrgs.length === 0 ? <tr className="govuk-table__row"><td className="govuk-table__cell" colSpan={5}>No role-level data for the selected range.</td></tr> : byRoleOrgs.map((row) => <tr className="govuk-table__row" key={row.organisationName}><th className="govuk-table__header" scope="row">{row.organisationName}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.applicantRequests)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.applicantPendingRequests)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.agentRequests)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.agentPendingRequests)}</td></tr>)}</tbody></table></TableRegion>
  </section>;
};

export const PaymentsReport = ({ metrics }: { metrics: MetricValues }) => <section className="reporting-section" id="payments" aria-labelledby="payments-heading"><h2 className="govuk-heading-l" id="payments-heading">Payments</h2><TableRegion label="Payment table"><table className="govuk-table"><caption className="govuk-visually-hidden">Payment number and value by form and payment method</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Form</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">GovPay number</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">GovPay value</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">BACS number</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">BACS value</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Total value</th></tr></thead><tbody className="govuk-table__body">{["s37", "nwl"].map((form) => { const govPayValue = metricValue(metrics, `${form}_govpay_value_pence`); const bacsValue = metricValue(metrics, `${form}_bacs_value_pence`); return <tr className="govuk-table__row" key={form}><th className="govuk-table__header" scope="row">{form.toUpperCase()}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_govpay_count`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(govPayValue / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_bacs_count`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(bacsValue / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format((govPayValue + bacsValue) / 100)}</td></tr>; })}<tr className="govuk-table__row"><th className="govuk-table__header" scope="row">Total</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_govpay_count", "nwl_govpay_count"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(metricTotal(metrics, "s37_govpay_value_pence", "nwl_govpay_value_pence") / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_bacs_count", "nwl_bacs_count"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(metricTotal(metrics, "s37_bacs_value_pence", "nwl_bacs_value_pence") / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(metricTotal(metrics, "s37_govpay_value_pence", "nwl_govpay_value_pence", "s37_bacs_value_pence", "nwl_bacs_value_pence") / 100)}</td></tr></tbody></table></TableRegion></section>;

export const FeedbackReport = ({ metrics }: { metrics: MetricValues }) => <section className="reporting-section" id="feedback" aria-labelledby="feedback-heading"><h2 className="govuk-heading-l" id="feedback-heading">Feedback</h2><dl className="govuk-summary-list"><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Received</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, "feedback_received"))}</dd></div></dl><h3 className="govuk-heading-s">Response breakdown</h3><TableRegion label="Feedback response breakdown table"><table className="govuk-table"><caption className="govuk-visually-hidden">Feedback satisfaction and ease response breakdown</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Measure</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Very positive</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Positive</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Neither</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Negative</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Very negative</th></tr></thead><tbody className="govuk-table__body">{[["Satisfaction", "feedback_satisfaction_very_satisfied", "feedback_satisfaction_satisfied", "feedback_satisfaction_neither", "feedback_satisfaction_dissatisfied", "feedback_satisfaction_very_dissatisfied"], ["Ease", "feedback_ease_very_easy", "feedback_ease_easy", "feedback_ease_neither_easy", "feedback_ease_difficult", "feedback_ease_very_difficult"]].map(([name, ...keys]) => <tr className="govuk-table__row" key={name}><th className="govuk-table__header" scope="row">{name}</th>{keys.map((key) => <td className="govuk-table__cell govuk-table__cell--numeric" key={key}>{formatNumber.format(metricValue(metrics, key))}</td>)}</tr>)}</tbody></table></TableRegion></section>;

export const RegistrationsReport = ({ metrics }: { metrics: MetricValues }) => <section className="reporting-section" id="registrations" aria-labelledby="registrations-heading">
  <h2 className="govuk-heading-l" id="registrations-heading">Registrations</h2>
  <p className="govuk-body reporting-period">Cumulative as of the end of the selected period.</p>
  <dl className="govuk-summary-list">
    <div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Total registrations</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, "registrations_total"))}</dd></div>
    <div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Unique application creators</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, "unique_application_creators"))}</dd></div>
  </dl>
  <TableRegion label="Registrations by status table"><table className="govuk-table"><caption className="govuk-visually-hidden">Registrations by status, split by applicant or agent role</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Status</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Total</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Applicant</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Agent</th></tr></thead><tbody className="govuk-table__body">{[["Approved", "registrations_approved"], ["Pending", "registrations_pending"], ["Rejected", "registrations_rejected"]].map(([name, key]) => <tr className="govuk-table__row" key={key}><th className="govuk-table__header" scope="row">{name}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, key))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${key}_applicant`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${key}_agent`))}</td></tr>)}</tbody></table></TableRegion>
</section>;

interface OrganisationBreakdownProps {
  organisations: OrganisationReportRow[];
  filter: string;
  onFilterChange: (value: string) => void;
  onDownload: () => void;
}

export const OrganisationBreakdown: React.FC<OrganisationBreakdownProps> = ({ organisations, filter, onFilterChange, onDownload }) => <section className="reporting-section" id="organisation-breakdown" aria-labelledby="organisations-heading"><div className="reporting-organisation-heading"><h2 className="govuk-heading-l" id="organisations-heading">Organisation breakdown</h2><button className="govuk-button govuk-button--secondary" type="button" onClick={onDownload}>Download CSV</button></div><div className="govuk-form-group"><label className="govuk-label govuk-label--s" htmlFor="organisation-filter">Find an organisation</label><input className="govuk-input govuk-input--width-20" id="organisation-filter" type="search" value={filter} onChange={(event) => onFilterChange(event.target.value)} /></div><p className="govuk-body-s" aria-live="polite">Showing {organisations.length} organisation{organisations.length === 1 ? "" : "s"}</p><TableRegion label="Organisation metrics table"><table className="govuk-table"><caption className="govuk-visually-hidden">Organisation metrics for the selected reporting period</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Organisation</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">S37 drafts</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">S37 submitted</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">NWL drafts</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">NWL submitted</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Access requests</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Pending</th></tr></thead><tbody className="govuk-table__body">{organisations.map((row) => <tr className="govuk-table__row" key={row.organisationName}><th className="govuk-table__header" scope="row">{row.organisationName}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.s37Draft)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.s37Submitted)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.nwlDraft)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.nwlSubmitted)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.accessRequests)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.pendingRequests)}</td></tr>)}</tbody></table></TableRegion></section>;

