import React from "react";
import { APPLICATION_STATUS_ROWS } from "../constants";
import { formatCurrency, formatNumber, metricTotal, metricValue } from "../reportingUtils";
import type { MetricValues, OrganisationReportRow, StatusColour } from "../types";
import { TableRegion } from "./ReportingControls";

const StatusTag = ({ name, colour }: { name: string; colour: StatusColour }) => <strong className={`govuk-tag govuk-tag--${colour} reporting-status-tag`}>{name}</strong>;

export const ReportingSummary = ({ metrics, startDate, endDate }: { metrics: MetricValues; startDate: string; endDate: string }) => (
  <section id="summary" aria-labelledby="summary-heading">
    <h2 className="govuk-heading-l" id="summary-heading">Summary</h2>
    <p className="govuk-body reporting-period">{startDate} to {endDate}</p>
    <dl className="reporting-summary-grid">
      <div><dt>Applications created</dt><dd>{formatNumber.format(metricTotal(metrics, "s37_created", "nwl_created"))}</dd></div>
      <div><dt>Applications submitted</dt><dd>{formatNumber.format(metricTotal(metrics, "s37_submitted", "nwl_submitted"))}</dd></div>
      <div><dt>Payments made</dt><dd>{formatNumber.format(metricTotal(metrics, "s37_govpay_count", "s37_bacs_count", "nwl_govpay_count", "nwl_bacs_count"))}</dd></div>
      <div><dt>Feedback received</dt><dd>{formatNumber.format(metricValue(metrics, "feedback_received"))}</dd></div>
      <div><dt>Access requests raised</dt><dd>{formatNumber.format(metricValue(metrics, "access_requests"))}</dd></div>
      <div><dt>Pending requests</dt><dd>{formatNumber.format(metricValue(metrics, "pending_requests"))}</dd></div>
    </dl>
  </section>
);

export const ApplicationsReport = ({ metrics }: { metrics: MetricValues }) => {
  const categoryMaximum = Math.max(1, ...APPLICATION_STATUS_ROWS.map(([, , s37Key, nwlKey]) => metricTotal(metrics, s37Key, nwlKey)));
  return <section className="reporting-section" id="applications" aria-labelledby="applications-heading">
    <h2 className="govuk-heading-l" id="applications-heading">Applications</h2><h3 className="govuk-heading-s">Activity</h3>
    <TableRegion label="Application activity table"><table className="govuk-table"><caption className="govuk-visually-hidden">Application activity by form</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Form</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Created</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Submitted</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Total</th></tr></thead><tbody className="govuk-table__body">{["s37", "nwl"].map((form) => <tr className="govuk-table__row" key={form}><th className="govuk-table__header" scope="row">{form.toUpperCase()}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_created`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_submitted`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, `${form}_created`, `${form}_submitted`))}</td></tr>)}<tr className="govuk-table__row"><th className="govuk-table__header" scope="row">Total</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_created", "nwl_created"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_submitted", "nwl_submitted"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_created", "nwl_created", "s37_submitted", "nwl_submitted"))}</td></tr></tbody></table></TableRegion>
    <figure className="reporting-category-chart" aria-labelledby="category-chart-heading"><figcaption className="govuk-heading-s" id="category-chart-heading">Applications by category</figcaption>{APPLICATION_STATUS_ROWS.map(([name, colour, s37Key, nwlKey]) => { const value = metricTotal(metrics, s37Key, nwlKey); return <div className="reporting-category-row" key={name}><span>{name}</span><div className="reporting-category-track" aria-hidden="true"><div className={`reporting-category-bar reporting-category-bar--${colour}`} style={{ width: `${(value / categoryMaximum) * 100}%` }} /></div><strong>{formatNumber.format(value)}</strong></div>; })}</figure>
    <TableRegion label="Application status table"><table className="govuk-table"><caption className="govuk-visually-hidden">Applications by status and form</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Status</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">S37</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">NWL</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Total</th></tr></thead><tbody className="govuk-table__body">{APPLICATION_STATUS_ROWS.map(([name, colour, s37Key, nwlKey]) => <tr className="govuk-table__row" key={name}><th className="govuk-table__header" scope="row"><StatusTag name={name} colour={colour} /></th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, s37Key))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, nwlKey))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, s37Key, nwlKey))}</td></tr>)}</tbody></table></TableRegion>
  </section>;
};

export const AccessRequestsReport = ({ metrics }: { metrics: MetricValues }) => <section className="reporting-section" id="access-requests" aria-labelledby="access-heading"><h2 className="govuk-heading-l" id="access-heading">Access requests</h2><dl className="govuk-summary-list">{[["Received", "access_requests"], ["Accepted", "accepted_requests"], ["Pending", "pending_requests"], ["Logged-in users", "logged_in_users"]].map(([label, key]) => <div className="govuk-summary-list__row" key={key}><dt className="govuk-summary-list__key">{label}</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, key))}</dd></div>)}</dl></section>;

export const PaymentsReport = ({ metrics }: { metrics: MetricValues }) => <section className="reporting-section" id="payments" aria-labelledby="payments-heading"><h2 className="govuk-heading-l" id="payments-heading">Payments</h2><TableRegion label="Payment table"><table className="govuk-table"><caption className="govuk-visually-hidden">Payment number and value by form and payment method</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Form</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">GovPay number</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">GovPay value</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">BACS number</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">BACS value</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Total value</th></tr></thead><tbody className="govuk-table__body">{["s37", "nwl"].map((form) => { const govPayValue = metricValue(metrics, `${form}_govpay_value_pence`); const bacsValue = metricValue(metrics, `${form}_bacs_value_pence`); return <tr className="govuk-table__row" key={form}><th className="govuk-table__header" scope="row">{form.toUpperCase()}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_govpay_count`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(govPayValue / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricValue(metrics, `${form}_bacs_count`))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(bacsValue / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format((govPayValue + bacsValue) / 100)}</td></tr>; })}<tr className="govuk-table__row"><th className="govuk-table__header" scope="row">Total</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_govpay_count", "nwl_govpay_count"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(metricTotal(metrics, "s37_govpay_value_pence", "nwl_govpay_value_pence") / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(metricTotal(metrics, "s37_bacs_count", "nwl_bacs_count"))}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(metricTotal(metrics, "s37_bacs_value_pence", "nwl_bacs_value_pence") / 100)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatCurrency.format(metricTotal(metrics, "s37_govpay_value_pence", "nwl_govpay_value_pence", "s37_bacs_value_pence", "nwl_bacs_value_pence") / 100)}</td></tr></tbody></table></TableRegion></section>;

export const FeedbackReport = ({ metrics }: { metrics: MetricValues }) => <section className="reporting-section" id="feedback" aria-labelledby="feedback-heading"><h2 className="govuk-heading-l" id="feedback-heading">Feedback</h2><dl className="govuk-summary-list"><div className="govuk-summary-list__row"><dt className="govuk-summary-list__key">Received</dt><dd className="govuk-summary-list__value">{formatNumber.format(metricValue(metrics, "feedback_received"))}</dd></div></dl><h3 className="govuk-heading-s">Response breakdown</h3><TableRegion label="Feedback response breakdown table"><table className="govuk-table"><caption className="govuk-visually-hidden">Feedback satisfaction and ease response breakdown</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Measure</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Very positive</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Positive</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Neither</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Negative</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Very negative</th></tr></thead><tbody className="govuk-table__body">{[["Satisfaction", "feedback_satisfaction_very_satisfied", "feedback_satisfaction_satisfied", "feedback_satisfaction_neither", "feedback_satisfaction_dissatisfied", "feedback_satisfaction_very_dissatisfied"], ["Ease", "feedback_ease_very_easy", "feedback_ease_easy", "feedback_ease_neither_easy", "feedback_ease_difficult", "feedback_ease_very_difficult"]].map(([name, ...keys]) => <tr className="govuk-table__row" key={name}><th className="govuk-table__header" scope="row">{name}</th>{keys.map((key) => <td className="govuk-table__cell govuk-table__cell--numeric" key={key}>{formatNumber.format(metricValue(metrics, key))}</td>)}</tr>)}</tbody></table></TableRegion></section>;

interface OrganisationBreakdownProps {
  organisations: OrganisationReportRow[];
  filter: string;
  onFilterChange: (value: string) => void;
  onDownload: () => void;
}

export const OrganisationBreakdown: React.FC<OrganisationBreakdownProps> = ({ organisations, filter, onFilterChange, onDownload }) => <section className="reporting-section" id="organisation-breakdown" aria-labelledby="organisations-heading"><div className="reporting-organisation-heading"><h2 className="govuk-heading-l" id="organisations-heading">Organisation breakdown</h2><button className="govuk-button govuk-button--secondary" type="button" onClick={onDownload}>Download CSV</button></div><div className="govuk-form-group"><label className="govuk-label govuk-label--s" htmlFor="organisation-filter">Find an organisation</label><input className="govuk-input govuk-input--width-20" id="organisation-filter" type="search" value={filter} onChange={(event) => onFilterChange(event.target.value)} /></div><p className="govuk-body-s" aria-live="polite">Showing {organisations.length} organisation{organisations.length === 1 ? "" : "s"}</p><TableRegion label="Organisation metrics table"><table className="govuk-table"><caption className="govuk-visually-hidden">Organisation metrics for the selected reporting period</caption><thead className="govuk-table__head"><tr className="govuk-table__row"><th className="govuk-table__header" scope="col">Organisation</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">S37 drafts</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">S37 submitted</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">NWL drafts</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">NWL submitted</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Access requests</th><th className="govuk-table__header govuk-table__header--numeric" scope="col">Pending</th></tr></thead><tbody className="govuk-table__body">{organisations.map((row) => <tr className="govuk-table__row" key={row.organisationName}><th className="govuk-table__header" scope="row">{row.organisationName}</th><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.s37Draft)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.s37Submitted)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.nwlDraft)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.nwlSubmitted)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.accessRequests)}</td><td className="govuk-table__cell govuk-table__cell--numeric">{formatNumber.format(row.pendingRequests)}</td></tr>)}</tbody></table></TableRegion></section>;

