export const ASSET_ERROR_MESSAGES = {
  referenceNumber: 'Enter the asset reference',
  lineType: 'Select the line type',
  lineLength: 'Enter the line length',
  addingPoles: 'Select yes if you are adding or replacing poles',
  polesAdded: 'Enter how many new poles you are adding',
  polesReplaced: 'Enter how many poles you are replacing',
  constructionDescription: 'Enter details about the poles you are adding or replacing',
  addingOverheadLines: 'Select yes if you are adding or replacing overhead lines',
  overheadLinesDescription: 'Enter details about overhead lines that will be added or replaced',
  removingEquipment: 'Select yes if you are adding or removing existing equipment',
  removingEquipmentDescription: 'Enter details about existing equipment that will be removed',
  worksOnExistingAsset: 'Select yes if works are to be carried out on an existing asset',
  lineVoltage: 'Select the line voltage',
  lineVoltageInvalid: 'Select a valid line voltage',
  generalCommentsFailed: 'Failed to save asset',
};
