// File category constants
export const FILE_CATEGORIES = {
	PLAN_INFO: 'PLAN_INFO',
	SUPPORT_INFO: 'SUPPORT_INFO',
	SENSITIVE_AREA_REVIEW: 'SENSITIVE_AREA_REVIEW',
	CONSULTATION_RESPONSE: 'CONSULTATION_RESPONSE',
	CONSULTATION_ADDITIONAL_DOCUMENTS: 'CONSULTATION_ADDITIONAL_DOCUMENTS',
	APPLICATION_LAND_DETAILS: 'APPLICATION_LAND_DETAILS',
};

export const FILE_CATEGORY_LABELS: { [key: string]: string } = {
	PLAN_INFO: 'Plan Information',
	SUPPORT_INFO: 'Support Information',
	CONSULTATION_RESPONSE: 'Consultation Response',
	SENSITIVE_AREA_REVIEW: 'Sensitive Area Review',
	CONSULTATION_ADDITIONAL_DOCUMENTS: 'Consultation Request Additional Documents',
};