// File category constants
export const FILE_CATEGORIES = {
	PLAN_INFO: 'PLAN_INFO',
	SUPPORT_INFO: 'SUPPORT_INFO',
	SENSITIVE_AREA_REVIEW: 'SENSITIVE_AREA_REVIEW',
	CONSULTATION_RESPONSE: 'CONSULTATION_RESPONSE',
	CONSULTATION_ADDITIONAL_DOCUMENTS: 'CONSULTATION_ADDITIONAL_DOCUMENTS',
	APPLICATION_LAND_DETAILS: 'APPLICATION_LAND_DETAILS',
	CONSULTATION_NOT_REQUIRED: 'CONSULTATION_NOT_REQUIRED',
};

export const FILE_CATEGORY_LABELS: { [key: string]: string } = {
	PLAN_INFO: 'Plan Information',
	SUPPORT_INFO: 'Support Information',
	CONSULTATION_RESPONSE: 'Consultation Response',
	SENSITIVE_AREA_REVIEW: 'Sensitive Area Review',
	CONSULTATION_ADDITIONAL_DOCUMENTS: 'Consultation Request Additional Documents',
};

export const NWL_FILE_CATEGORIES = {
	NEGOTIATIONS: 'NEGOTIATIONS',
	SIGNED_WAYLEAVE: 'SIGNED_WAYLEAVE',
	INHERITED_WAYLEAVE: 'INHERITED_WAYLEAVE',
	ANY_PAYMENTS: 'ANY_PAYMENTS',
	ACCEPTED_PAYMENTS: 'ACCEPTED_PAYMENTS',
	WRITTEN_TERMINATION_NOTICE: 'WRITTEN_TERMINATION_NOTICE',
	WRITTEN_TERMINATION: 'WRITTEN_TERMINATION',
	WRITTEN_REMOVAL: 'WRITTEN_REMOVAL',
	TITLE_PLAN: 'TITLE_PLAN',
};