
export const ROLES = {
  APPLICANT: "Applicant",
  APPLICANT_AGENT: "APPLICANT_AGENT",
  APPLICANT_USER: "APPLICANT_USER",
  NETWORK_OPERATOR: "Network operator",
  CONTACT: "Contact",
  SUPERUSER: "SUPERUSER",
  APPLICANT_TEAM_COORDINATOR: "APPLICANT_TEAM_COORDINATOR",
  TECH_ADMIN: "TECH_ADMIN",
};
