export const ROLES = {
  APPLICANT: "Applicant",
  NETWORK_OPERATOR: "Network operator",
  CONTACT: "Contact",
  DESNZ_ADMIN: "DESNZ_ADMIN",
  APPLICANT_TEAM_COORDINATOR: "APPLICANT_TEAM_COORDINATOR",
};
