export const APPLICATION_STATUS = {
  DRAFT: 'Draft',
  SUBMITTED: 'Submitted',
  IN_REVIEW: 'In review',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  COMPLETED: 'Completed',
  INCOMPLETE: 'Incomplete',
  CANNOT_START_YET: 'Cannot start yet',
  NOT_COMPLETED: 'Not completed',
  ON_HOLD: 'On hold',
  DECLINED: 'Declined',
  NEGOTIATED: 'Negotiated',
  PAYMENT_PENDING: 'Payment pending',
  GRANTED: 'Granted',
  HEARING_PENDING: 'Hearing pending',
};