export const WORKS_OVERVIEW_LABELS = {
  ADDING_REPLACING_POLES: 'Are you adding or replacing any poles?',
  POLE_MATERIAL: 'What materials will be used for the new poles or pylons?',
  CHEMICAL_TREATMENTS: 'Are any chemical coatings proposed?',
  POLES_ADDED: 'How many poles are you adding?',
  POLES_REPLACED: 'How many poles are you replacing?',
  TALLEST_NEW_POLE_HEIGHT: 'What height is the tallest new pole?',
  TALLEST_NEW_POLE_HEIGHT_HINT: 'If not, answer 0',
  POLE_COMMENTS: 'Comments on pole placement, colour or replacement (optional)',
  ADDING_REPLACING_LINES: 'Are you adding or replacing any overhead lines?',
  OVERHEAD_LINE_DESCRIPTION: 'Provide a description of the overhead lines that you are adding or replacing',
  ESTIMATED_DURATION: 'What is the estimated duration of the works?',
  VEHICLES_REQUIRED: 'What vehicles will be required on site?',
  ROAD_CLOSURES: 'Will any road closures or traffic calming measures be required?',
  ROAD_CLOSURES_DETAILS: 'Please provide details of the road measures, some helpful advice text, road, times, durations.',
  ROAD_CLOSURES_DOCUMENTS: 'Upload any documents related to discussions with the highway authority',
  EXCAVATION_REQUIRED: 'Are excavation works required?',
  EXCAVATION_HINT: 'For example for cable laying or pole installation',
  EXCAVATION_DETAILS: 'Provide more details about the excavation work.',
  VEGETATION_CLEARANCE: 'Is vegetation clearance required?',
  VEGETATION_HINT: 'For example hedgerow removal or tree lopping',
  VEGETATION_DETAILS: 'Provide more details about the vegetation clearance.',
  REMOVING_EQUIPMENT: 'Are you removing any existing equipment as part of this project?',
  REMOVAL_DESCRIPTION: 'Provide a description of the equipment you are removing',
} as const;
